### ISSUE TITLE
Handle permissions

### ISSUE THREAD

**Issue by mathebox** [schul-cloud/schulcloud-mobile-ios#113]
- There are multiple permission for different roles that should be respected within the app
- see https://schul-cloud.org:8080/roles and the `roles` attribute on the user model
- if the request is done anyway, the server will respond with status code `403`
- The UI should be designed accordingly, either showing an alert (good for demo modus) or hiding the specific controls

**Comment by Einh06** [comment]
As a note reference for implementation, what needs to be done:
- Customize which tab is shown in the main `UITabBarController` based on the permission ( show the `News` tab when `NEWS_VIEW` is allowed etc`
- Always have the dashboard visible, but control which sub-controller are shown based on permission, event if it is empty (it's an extreme edge case that would simply break the app if allowed, I don't think that should be)
- Handle the possibility of creating / editing / removing on a per controller base (e.g FilesViewController for example). Each controller affected by permissions will be marked with `TODO(permissions)` until implemented

It is important to use reason. Having the permission for certain actions doesn't mean the app should handle it (e.g. News creation), It needs to make sense.
