### ISSUE TITLE
Homework Overview improve design

### ISSUE THREAD

**Issue by Einh06** [schul-cloud/schulcloud-mobile-ios#124]
The `HomeworkOverviewViewController` would benefit from small improvement in its design. It so far only shows how many homework are due in the next week.
This will be changed to display how many homeworks are due in the next 2days, and also display a list of assignments due per subject ( Math (3), Biologie (2)).
This will make the overview more useful, showing more relevant information.

**Comment by mathebox** [comment]
Implemented in #133
