### ISSUE TITLE
Revise styling of task list

### ISSUE THREAD

**Issue by mathebox** [schul-cloud/schulcloud-mobile-ios#15]
consider color of classes

**Comment by MasterCarl** [comment]
<img width="605" alt="screen shot 2017-08-14 at 17 48 45" src="https://user-images.githubusercontent.com/6067572/29279657-de3db506-8118-11e7-8789-b293b782aed2.png">
Here's a mockup. Thoughts?

**Comment by mathebox** [comment]
Look good. But I'm afraid this would take to much time to implement for the MVP. I would suggest to stick to a more basic design for now. But definitely keep this in mind!

Also, we could face some problems with the (user picked) colors and the readability of the course names. Therefore, we should separate course color and course title visually (for now).
