### ISSUE TITLE
Show list news articles 

### ISSUE THREAD

**Issue by mathebox** [schul-cloud/schulcloud-mobile-ios#92]
**Expected Behavior:**
- show list of news articles in separate tab in tab bar
  - use `favorites` tab bar icon (star) (might be changed later)
- use a table view
- no detail view required. put everything in a table view cell

**Additional Notes:**
url: `https://schul-cloud.org:8080/news`

**Comment by Einh06** [comment]
Can be consider this issue closed?

**Comment by mathebox** [comment]
Yes
